// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jhay Pizzas | Buffet de Pizza Gourmet em Domicílio - Palmas, TO",
  description: "A Jhay Pizzas leva o autêntico rodízio de pizzas artesanais para o seu evento em Palmas. Massa de longa fermentação, ingredientes premium e pizzaiolo profissional. Solicite seu orçamento!",
  keywords: "pizza gourmet palmas, buffet pizza domicílio, rodízio pizza palmas, pizza artesanal, festa pizza, evento pizza palmas",
  openGraph: {
    title: "Jhay Pizzas | Buffet de Pizza Gourmet em Domicílio",
    description: "Transforme sua casa na melhor pizzaria de Palmas. Pizzas artesanais com massa de 48h de fermentação.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
